Repository SV-Summer-BootCamp-Team-F/frontend, pull requests merged in 2023-08, with the labels that each got.

#61 Feature/new enroll page api 56
  src/pages/Card/EnrollPage.tsx
  src/pages/Card/NewEnrollPage.tsx
Labels: feature

#65 Feature/enroll page componentize 62
  src/pages/Card/EnrollPage.tsx
  src/pages/Card/NewEnrollPage.tsx
Labels: bugfix

#68 Feature/relation page api integration 51
  README.md
  package.json
  src/components/card/CardInfo.tsx
  src/components/card/CardPhotoUpdateModal.tsx
  src/components/relation/ChartContent.tsx
  src/components/user/UserPhotoUpdateModal.tsx
  src/components/user/UserProfile.tsx
  src/domain/domain.ts
  src/pages/Card/EnrollPage.tsx
  src/pages/Card/NewEnrollPage.tsx
  src/pages/Login/LoginPage.tsx
  src/pages/Login/SignupPage.tsx
  src/pages/Relation/RelationPage.tsx
  src/pages/User/UserPage.tsx
  src/pages/User/techeer_ad.png
  src/pages/test/TestPage.tsx
  src/utils/fetchRelations.ts
  yarn.lock
Labels: feature

#74 Design/update design relation page 69
  package.json
  src/components/card/CardInfo.tsx
  src/components/card/CardPhotoUpdateModal.tsx
  src/components/intro/Sphere.tsx
  src/components/main/ButtonEnrollModal.tsx
  src/components/relation/CardDetail.tsx
  src/components/relation/CardShowModal.tsx
  src/components/relation/Chart.tsx
  src/components/relation/ChartContent.tsx
  src/components/relation/RelationModal.tsx
  src/components/relation/Sky.css
  src/components/relation/Sky.tsx
  src/components/relation/Star.tsx
  src/components/relation/ZoomableSVG.tsx
  src/components/relation/remember_plus_background.gif
  src/components/user/UserPhotoUpdateModal.tsx
  src/components/user/UserProfile.tsx
  src/css/Modal.css
  src/domain/domain.ts
  src/pages/Card/NewEnrollPage.tsx
  src/pages/User/UserPage.tsx
  src/pages/User/final_ad.png
  src/pages/test/TestPage.tsx
  src/types/types.ts
  src/utils/fetchRelations.ts
  yarn.lock
Labels: feature, design
