Repository SV-Summer-BootCamp-Team-F/frontend, pull requests merged in 2023-07, with the labels that each got.

#2 docs: README.md 파일 추가
  README.md
Labels: docs

#4 chore: rem 단위 재설정, tailwindcss 초기 세팅
  src/index.css
  tailwind.config.cjs
Labels: chore

#9 Chore/PR Template 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#12 !HOTFIX: .prettierrc.cjs 파일 수정
  .prettierrc.cjs
Labels: !!HOTFIX, chore, SELF-MERGED

#16 !HOTFIX: tailwindcss 설정 오류 수정
  package.json
  postcss.config.js
  src/App.tsx
  src/index.css
  src/pages/test/TestPage.tsx
  tailwind.config.cjs
  tailwind.config.js
  yarn.lock
Labels: bugfix, !!HOTFIX, chore

#13 Design/publishing relation page
  package.json
  src/App.tsx
  src/components/relation/Chart.tsx
  src/components/relation/ChartContent.tsx
  src/components/relation/RelationGraph.tsx
  src/components/relation/ZoomableSVG.tsx
  src/pages/Relation/RelationPage.tsx
  src/types/types.ts
  src/utils/generateDataPoints.ts
  yarn.lock
Labels: feature, design

#17 Design/publishing user information page
  package.json
  src/App.tsx
  src/pages/User/UserPage.tsx
  src/pages/User/components/CardInfo.tsx
  src/pages/User/components/LineChart.tsx
  src/pages/User/components/PieChart.tsx
  src/pages/User/components/UserProfile.tsx
  yarn.lock
Labels: design

#18 Design/publishing enroll page
  README.md
  package.json
  src/App.tsx
  src/pages/Card/EnrollPage.tsx
  src/pages/LoginPage.tsx
  src/pages/SecondPage.tsx
  yarn.lock
Labels: design

#24 !HOTFIX: fix tailwindconfigjs
  src/pages/test/TestPage.tsx
  tailwind.config.js
Labels: bugfix, !!HOTFIX, chore

#20 design/main page publishing
  package.json
  src/App.tsx
  src/components/Button.tsx
  src/components/Profile.tsx
  src/components/Text.tsx
  src/components/Text2.tsx
  src/components/intro/Anychart.tsx
  src/components/intro/Profile.tsx
  src/components/intro/Slide.tsx
  src/components/intro/Sphere.tsx
  src/components/intro/Text.tsx
  src/components/main/Card.tsx
  src/components/main/Phone.tsx
  src/css/Card.css
  src/css/Login.css
  src/css/Profile.css
  src/css/Scroll.css
  src/css/Signup.css
  src/css/Text.css
  src/index.css
  src/pages/IntroPage.tsx
  src/pages/MainPage.tsx
  src/pages/StartPage.tsx
  src/pages/User/UserPage.tsx
  yarn.lock
Labels: design

#25 Design/design update user information page 21
  package.json
  src/components/analytic/BarChart.tsx
  src/components/analytic/LineChart.tsx
  src/components/analytic/PieChart.tsx
  src/components/analytic/StatisticsBox.tsx
  src/components/card/CardInfo.tsx
  src/components/card/CardPhoto.tsx
  src/components/user/UserProfile.tsx
  src/pages/User/UserPage.tsx
  src/pages/User/components/CardInfo.tsx
  src/pages/User/components/LineChart.tsx
  src/pages/User/components/UserProfile.tsx
  yarn.lock
Labels: design

#29 style: NEW RULE: PATH ENDPOINT
  src/App.tsx
Labels: chore

#37 Feature/UserPage new apply
  package.json
  public/mockServiceWorker.js
  src/components/analytic/BarChart.tsx
  src/components/analytic/IntroLineChart.tsx
  src/components/analytic/LineChart.tsx
  src/components/analytic/PieChart.tsx
  src/components/analytic/StatisticsBox.tsx
  src/components/analytic/ThreeDPieChart.tsx
  src/components/card/CardInfo.tsx
  src/components/card/CardInfoUpdateModal.tsx
  src/components/card/CardPhoto.tsx
  src/components/card/CardPhotoUpdateModal.tsx
  src/components/card/EnrollCheckModal.tsx
  src/components/user/UserInfoUpdateModal.tsx
  src/components/user/UserProfile.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/pages/User/UserPage.tsx
  src/pages/test/TestPage.tsx
  yarn.lock
Labels: feature, bugfix

#45 Design/changed and simplification
  src/App.tsx
  src/components/analytic/BarChart.tsx
  src/components/analytic/IntroLineChart.tsx
  src/components/analytic/PieChart.tsx
  src/components/analytic/ThreeDPieChart.tsx
  src/components/card/CardInfo.tsx
  src/components/card/Modal.tsx
  src/components/intro/Text.tsx
  src/components/main/Button.tsx
  src/pages/Card/EnrollPage.tsx
  src/pages/Card/NewEnrollPage.tsx
  src/pages/Login/LoginPage.tsx
  src/pages/Login/SignupPage.tsx
  src/pages/MainPage.tsx
  src/pages/User/UserPage.tsx
  src/planet/license.txt
  src/planet/scene.bin
  src/planet/scene.gltf
  src/planet/textures/Clouds_baseColor.png
  src/planet/textures/Planet_baseColor.png
Labels: design, refactor

#48 Feat/relation api 43
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/components/analytic/BarChart.tsx
  src/components/analytic/IntroLineChart.tsx
  src/components/analytic/LineChart.tsx
  src/components/analytic/PieChart.tsx
  src/components/analytic/ThreeDPieChart.tsx
  src/components/card/CardInfo.tsx
  src/components/card/CardInfoUpdateModal.tsx
  src/components/card/CardPhotoUpdateModal.tsx
  src/components/card/Modal.tsx
  src/components/intro/Text.tsx
  src/components/main/Button.tsx
  src/components/relation/ZoomableSVG.tsx
  src/components/user/UserInfoUpdateModal.tsx
  src/components/user/UserPhotoUpdateModal.tsx
  src/components/user/UserProfile.tsx
  src/pages/Card/EnrollPage.tsx
  src/pages/Card/NewEnrollPage.tsx
  src/pages/Login/LoginPage.tsx
  src/pages/Login/SignupPage.tsx
  src/pages/MainPage.tsx
  src/pages/User/UserPage.tsx
  src/pages/test/TestPage.tsx
  src/planet/license.txt
  src/planet/scene.bin
  src/planet/scene.gltf
  src/planet/textures/Clouds_baseColor.png
  src/planet/textures/Planet_baseColor.png
Labels: feature

#50 Feature/enroll page mocking 27
  src/pages/Card/EnrollPage.tsx
  src/pages/Card/NewEnrollPage.tsx
Labels: bugfix

#55 Feature/명함 등록 modal 창 생성 55
  src/components/main/Button.tsx
  src/components/main/ButtonEnrollModal.tsx
  src/pages/Card/EnrollPage.tsx
  src/pages/MainPage.tsx
Labels: feature

#57 Feature/user information page api integragion 46
  src/components/card/CardInfo.tsx
  src/components/card/CardInfoUpdateModal.tsx
  src/components/card/CardPhotoUpdateModal.tsx
  src/components/user/UserInfoUpdateModal.tsx
  src/components/user/UserPhotoUpdateModal.tsx
  src/components/user/UserProfile.tsx
  src/mocks/browser.tsx
  src/mocks/handlers.tsx
  src/pages/Card/EnrollPage.tsx
  src/pages/User/UserPage.tsx
  src/pages/test/TestPage.tsx
Labels: feature

#58 Feature/relation page api integration 53
  src/components/relation/Chart.tsx
  src/components/relation/ChartContent.tsx
  src/components/relation/RelationGraph.tsx
  src/mocks/handlers.ts
  src/types/types.ts
  src/utils/fetchRelations.ts
Labels: feature, design

#59 Design/update design highchart and user information page 40
  .eslintrc.cjs
  src/App.css
  src/App.tsx
  src/components/analytic/BarChart.tsx
  src/components/analytic/IntroLineChart.tsx
  src/components/analytic/LineChart.tsx
  src/components/analytic/PieChart.tsx
  src/components/analytic/ThreeDPieChart.tsx
  src/components/card/CardInfo.tsx
  src/components/card/CardInfoUpdateModal.tsx
  src/components/card/CardPhotoUpdateModal.tsx
  src/components/main/Button.tsx
  src/components/user/UserInfoUpdateModal.tsx
  src/components/user/UserPhotoUpdateModal.tsx
  src/components/user/UserProfile.tsx
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/pages/Card/NewEnrollPage.tsx
  src/pages/User/UserPage.tsx
  src/pages/User/ad.png
  src/pages/test/TestPage.tsx
Labels: design

#60 Design/to korean from english and modal 54
  README.md
  src/components/analytic/IntroLineChart.tsx
  src/components/analytic/ThreeDPieChart.tsx
  src/components/intro/Slider.tsx
  src/components/intro/Text.tsx
  src/components/main/Button.tsx
  src/components/main/ButtonEnrollModal.tsx
  src/components/relation/ZoomableSVG.tsx
  src/components/user/UserPhotoUpdateModal.tsx
  src/pages/Card/EnrollPage.tsx
  src/pages/Card/NewEnrollPage.tsx
  src/pages/MainPage.tsx
Labels: feature, design, refactor
